#!/usr/bin/env python
#   openstack-parallel OBJECT[,OBJECT ...] ARGS ... PATTERN
# e.g.
#   openstack-parallel server,port delete test-cluster

import sys, json, subprocess, pprint

if __name__ == '__main__':
    input_object = sys.argv[1]
    pattern = sys.argv[-1]
    print('object=%s pattern=%s' % (input_object, pattern))

    if ',' in input_object:
        cmd_objects = input_object.split(',')
    else:
        cmd_objects = [input_object]
    
    cmds = []
    for cmd_object in cmd_objects:
        p = subprocess.run("openstack %s list -f json" % cmd_object, shell=True, capture_output=True, text=True)
        objects = json.loads(p.stdout)
        filtered_objects = [ob for ob in objects if pattern in ob['Name']]
        for ob in filtered_objects:
            cmd = ['openstack', cmd_object] + sys.argv[2:-1] + [ob['Name']]
            cmds.append(' '.join(cmd))
    if len(cmds) == 0:
        sys.exit("No %s matching '%s' found." % (input_object, pattern))
    else:
        print('Running:')
        for cmd in cmds:
            print(cmd)
    go = input('Proceed? (y/n):')
    if go == "y":
        for cmd in cmds:
            print(cmd + ':')
            p = subprocess.run(cmd, shell=True, capture_output=True, text=True)
            print(p.stdout)
